version: "3.9"  # optional since v1.27.0
services:
  bot:
    build: .
    env_file: .env
    environment:
      REDIS_URL: "redis://redis:6379/1"
    depends_on:
      - redis

  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
